### ISSUE TITLE
Please rename the master branch to the main branch.

### ISSUE THREAD

**Issue by rhatdan** [containers/docker-lvm-plugin#101]

**Comment by shishir-a412ed** [comment]
@rhatdan Fixed.
<img width="1191" alt="Screen Shot 2021-05-13 at 8 56 43 PM" src="https://user-images.githubusercontent.com/4207652/118219148-bc437e80-b42d-11eb-8009-42dbbe9cfdbd.png">

**Comment by rhatdan** [comment]
Thanks.
