### ISSUE TITLE
RHEL7 `docker ls` does not autostart lvm plugin module

### ISSUE THREAD

**Issue by erikbgithub** [containers/docker-lvm-plugin#42]
$ docker volume ls
    DRIVER      VOLUME NAME
    [...]
    $ systemctl status docker-lvm-plugin
    [...]
    Loaded: loaded [...]
    Active: inactive (dead)

installed on RHEL 7.4 via `yum install`. Version `docker-lvm-plugin.x86_64 2:1.12.6-71.git3e8e77d.el7`.

**Comment by shishir-a412ed** [comment]
@erikbgithub Are you still facing this issue?

1) Can you show me the systemd unit file for `docker-lvm-plugin` ?
$$ systemctl cat docker-lvm-plugin.

2) Output of:
$$ ls /run/docker/plugins -lt

**Comment by shishir-a412ed** [comment]
@erikbgithub closing it due to inactivity. Please feel free to reopen if you are still facing the issue.
