### ISSUE TITLE
lvremove without lvchange

### ISSUE THREAD

**Issue by mortya** [containers/docker-lvm-plugin#64]
I notice that the code does an `lvremove --force $device` instead of `lvchange -a n $device` followed by `lvremove $device`.  I think the latter is usually preferred.  This might be deliberate on your part, though, if you want to do the remove as a single atomic action.  Heads up, just in case.

**Comment by shishir-a412ed** [comment]
@mortya PR's are welcome :)

**Comment by shishir-a412ed** [comment]
Keeping it as an atomic operation `lvremove --force $device` for now.
