### ISSUE TITLE
make file assumes go-md2man is present and in path

### ISSUE THREAD

**Issue by nickbreen** [containers/docker-lvm-plugin#75]
Problem encountered in golang/1.8 and golang/1.12.5 docker containers, and also on ubuntu disco.

On ubuntu `apt install go-md2man` provided the tool.

The `Makefile` should include an env/var for go-md2man as it does with `GOLANG`.

**Comment by shishir-a412ed** [comment]
Even if I add the env/var for `go-md2man` in the Makefile, something like:

````
GOLANG ?= /usr/bin/go
GOMD2MAN ?= /usr/bin/go-md2man
````

you would still have to install `go-md2man`.
If `go-md2man` is missing on the system, it will throw an error.

Once you install the tool, it's by default in the $PATH (/usr/bin), so no variable needed in the Makefile.
