### ISSUE TITLE
Plugin "lvm" not found

### ISSUE THREAD

**Issue by jojaii** [containers/docker-lvm-plugin#81]
Hi all, I just installed the plugin and I am testing lvm creation using:

`docker volume create -d lvm --opt size=0.2G --name foobar`

But I am receiving the following error:

`Error response from daemon: create foobar: error looking up volume plugin lvm: plugin "lvm" not found`

I have correctly configured the _/etc/docker/docker-lvm-plugin_ and made only one minor configuration to the _Makefile_ (changed `GOLANG` to my `$GOPATH` which is
`GOLANG ?= /usr/local/go/bin/go`).

Can anybody guide me where I might have gone wrong? I am guessing this might have to do with the recently released **go 1.13** version but I haven't confirmed it yet. Will update this when I am able to do so.

**Comment by jojaii** [comment]
Downgraded my go version to **1.12.9** but still having the same issue. Does anybody have any idea what I might be doing wrong? Is there perhaps a specific Go version that I should downgrade to?

**Comment by shishir-a412ed** [comment]
@jojaii Looks like docker daemon is not able to find the plugin. Is the plugin running?

Can you paste the output of:

1) cat /etc/os-release
2) systemctl status docker-lvm-plugin

**Comment by jojaii** [comment]
Thank you for the reply @shishir-a412ed 

Here's the output for cat /etc/os-release:
`NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
`


And here's the output for systemctl status docker-lvm-plugin:
`
● docker-lvm-plugin.service - Docker Volume Driver for lvm volumes
   Loaded: loaded (/usr/lib/systemd/system/docker-lvm-plugin.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-09-23 09:00:17 PST; 2 days ago
     Docs: man:docker-lvm-plugin(8)
  Process: 1089 ExecStart=/usr/libexec/docker/docker-lvm-plugin (code=exited, status=1/FAILURE)
 Main PID: 1089 (code=exited, status=1/FAILURE)
Sep 23 09:00:17 PHL-B60SRN2 systemd[1]: Started Docker Volume Driver for lvm volumes.
Sep 23 09:00:17 PHL-B60SRN2 docker-lvm-plugin[1089]: time="2019-09-23T09:00:17+08:00" level=fatal msg="mkfs.xfs is not available, please install xfsprogs to continue"
Sep 23 09:00:17 PHL-B60SRN2 systemd[1]: docker-lvm-plugin.service: Main process exited, code=exited, status=1/FAILURE
Sep 23 09:00:17 PHL-B60SRN2 systemd[1]: docker-lvm-plugin.service: Unit entered failed state.
Sep 23 09:00:17 PHL-B60SRN2 systemd[1]: docker-lvm-plugin.service: Failed with result 'exit-code'.
`

**Comment by shishir-a412ed** [comment]
@jojaii `msg="mkfs.xfs is not available, please install xfsprogs to continue"`
May be install `xfsprogs` :) ?

**Comment by jojaii** [comment]
I couldn't for the life of me figure out how to debug this at first! Turns out `systemctl status` was all I needed. Thank you for your help @shishir-a412ed .
