### ISSUE TITLE
README.md have small typo

### ISSUE THREAD

**Issue by Rim13** [containers/docker-lvm-plugin#87]
At pt. 3 create **vg0**
At pt. 5 used **vg1**

> 5. The docker-lvm-plugin also supports the creation of thinly-provisioned volumes. To create a thinly-provisioned volume, a user (administrator) must first create a thin pool using the lvcreate command.
> `lvcreate -L 10G -T vg1/mythinpool`

**Comment by shishir-a412ed** [comment]
@Rim13 Nice catch! PRs are welcome 😊

Point (5) example needs to be changed to **vg0**
